services:
  database:
    image: postgres:17.6
    container_name: pastebin_database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - default
    restart: always

  redis:
    image: redis:8.2.1
    container_name: pastebin_redis
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

volumes:
  database_data:

networks:
  default:
    driver: bridge
