services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastebin_api
    environment:
      ENV: ${ENV}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - database
      - cache
    networks:
      - default

  database:
    image: postgres:17.6
    container_name: pastebin_database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - default
    restart: always

  cache:
    image: redis:8.2.1
    container_name: pastebin_cache
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default
    restart: always

volumes:
  database_data:

networks:
  default:
    driver: bridge
