CREATE TABLE IF NOT EXISTS pastes (
  id UUID PRIMARY KEY UNIQUE,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  lang VARCHAR(50) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
