apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pastebin-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
