name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Load env
        run: |
          if [ -f .env ]; then
            export $(cat .env.test | grep -v '^#' | xargs)
          fi

      - name: Run tests
        run: go test -v ./...
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_WAIT_TIMEOUT: 60s
